### ISSUE TITLE
404 blsttc in cargo

### ISSUE THREAD

**Issue by katopz** [LIT-Protocol/cloudflare-litgate-rust#1]
Refer to https://github.com/LIT-Protocol/cloudflare-litgate-rust/blob/ce345a648a287ebf5ba905bffe827b98b2f0faba/Cargo.toml#L23

but [https://github.com/LIT-Protocol/blsttc](https://github.com/LIT-Protocol/blsttc) seem to be `404`?

**Comment by glitch003** [comment]
Apologies, that repo was private.  I just made it public.  This should now work for you.
